const {useEffect,useState}=React;
const POS={Portero:['atajadas','goles_recibidos','porterias_cero'],Defensa:['intercepciones','despejes','bloqueos','recuperaciones'],Lateral:['intercepciones','centros','centros_acertados'],Mediocampista:['pases','pases_acertados','pases_clave','ocasiones_creadas'],Extremo:['regates_intentados','regates_exitosos','centros','tiros','tiros_arco'],Delantero:['tiros','tiros_arco','regates','regates_exitosos','penaltis_convertidos']};
const GEN=['partidos','goles','asistencias','mvp','victorias','empates','derrotas'];
function App(){const [session,S]=useState(null),[authReady,AR]=useState(false),[tab,T]=useState('Inicio'),[players,P]=useState([]),[matches,M]=useState([]),[requests,R]=useState([]),[notes,N]=useState([]),[modal,D]=useState(null),[msg,G]=useState('');const me=players.find(p=>p.id===session?.user?.id);
const toast=x=>{G(x);setTimeout(()=>G(''),3000)};
async function load(){try{const [p,m,r,n]=await Promise.all([MatchdayAPI.players(),MatchdayAPI.matches(),MatchdayAPI.requests(),MatchdayAPI.notifications()]);P(p||[]);M(m||[]);R(r||[]);N(n||[])}catch(e){toast(e.message)}}
useEffect(()=>{let alive=true,received=false;const apply=s=>{if(!alive)return;received=true;S(s||null);AR(true)};const {data:{subscription}}=window.supabaseClient.auth.onAuthStateChange((_e,s)=>apply(s));window.supabaseClient.auth.getSession().then(({data,error})=>{if(!received&&!error)apply(data.session)}).catch(()=>{if(alive)AR(true)});return()=>{alive=false;subscription.unsubscribe()}},[]);
useEffect(()=>{if(session)load()},[session]);
useEffect(()=>{if(!session)return;const c=window.supabaseClient.channel('matchday-react').on('postgres_changes',{event:'*',schema:'public',table:'profiles'},load).on('postgres_changes',{event:'*',schema:'public',table:'matches'},load).on('postgres_changes',{event:'*',schema:'public',table:'match_requests'},load).subscribe();return()=>window.supabaseClient.removeChannel(c)},[session]);
const refresh=async()=>{await load();D(null)};
if(!authReady)return <main><section><h1>MATCHDAY</h1><p className="sub">Comprobando tu sesión...</p></section></main>;
if(!session)return <Auth toast={toast} onAuth={S}/>;
const createNotification=async texto=>{try{await window.supabaseClient.from('notifications').insert({user_id:session.user.id,texto})}catch{}};
return <><aside><div className="logo">MATCH<b>DAY</b></div><nav>{['Inicio','Partidos','Jugadores','Avisos'].map(x=><button key={x} className={tab===x?'on':''} onClick={()=>T(x)}>{x}</button>)}<button onClick={()=>window.supabaseClient.auth.signOut()}>Cerrar sesión</button></nav></aside><main><div className="row" style={{justifyContent:'space-between',marginBottom:20}}><div><b>{session.user.email}</b><div className="lbl">{me?'Perfil: '+me.nombre:'Cuenta sin perfil de jugador'}</div></div>{!me&&<button className="btn" onClick={()=>D({kind:'player'})}>Crear mi perfil</button>}</div>
{tab==='Inicio'&&<><h1>Inicio</h1><p className="sub">Crear · Encontrar · Jugar · Registrar · Analizar</p><div className="row"><button className="btn" onClick={()=>D({kind:'match'})}>Crear partido</button><button className="btn g" onClick={()=>T('Partidos')}>Buscar partido</button></div>{me?<><h2>Mi resumen · {me.nombre}</h2><div className="grid">{[['Partidos',me.stats?.partidos],['Victorias',me.stats?.victorias],['Goles',me.stats?.goles],['Asistencias',me.stats?.asistencias]].map(a=><div className="card" key={a[0]}><div className="stat">{a[1]||0}</div><div className="lbl">{a[0]}</div></div>)}</div><button className="btn g" style={{marginTop:12}} onClick={()=>D({kind:'player',existing:me})}>Editar mi perfil</button></>:<div className="empty">Crea tu perfil de jugador para empezar.</div>}<h2>Próximos partidos</h2>{matches.slice(0,3).map(m=><MatchCard key={m.id} m={m} session={session} me={me} reqs={requests} edit={()=>D({kind:'match',existing:m})} join={()=>D({kind:'join',match:m})} remove={async()=>{if(m.owner_id!==session.user.id)return toast('No puedes eliminar el partido de otra persona');if(confirm('¿Eliminar este partido?'))try{await MatchdayAPI.deleteMatch(m.id);toast('Partido eliminado');load()}catch(e){toast(e.message)}}}/>)}{!matches.length&&<div className="empty">No hay partidos todavía. ¡Crea el primero!</div>}</>}
{tab==='Partidos'&&<><h1>Partidos</h1><p className="sub">Partidos de la comunidad</p><button className="btn" onClick={()=>D({kind:'match'})}>+ Crear partido</button><div className="grid" style={{marginTop:14}}>{matches.map(m=><MatchCard key={m.id} m={m} session={session} me={me} reqs={requests} edit={()=>D({kind:'match',existing:m})} join={()=>D({kind:'join',match:m})} remove={async()=>{if(m.owner_id!==session.user.id)return toast('No puedes eliminar el partido de otra persona');if(confirm('¿Eliminar este partido?'))try{await MatchdayAPI.deleteMatch(m.id);load()}catch(e){toast(e.message)}}}/>)}{!matches.length&&<div className="empty">No hay partidos todavía. ¡Crea el primero!</div>}</div></>}
{tab==='Jugadores'&&<><h1>Jugadores</h1><p className="sub">Cada persona administra su propio perfil.</p>{me?<button className="btn" onClick={()=>D({kind:'player',existing:me})}>Editar mi perfil</button>:<button className="btn" onClick={()=>D({kind:'player'})}>Crear mi perfil</button>}<div className="grid" style={{marginTop:14}}>{players.map(p=><div className="card" key={p.id}><div className="lbl">#{p.num||'-'} · {p.pos}</div><h3>{p.nombre}</h3><div className="lbl">{p.equipo||'Sin equipo'}</div><button className="btn s g" style={{marginTop:10}} onClick={()=>D({kind:'view',player:p})}>{p.id===session.user.id?'Mi perfil':'Ver perfil'}</button>{p.id===session.user.id&&<button className="btn s" style={{marginLeft:6}} onClick={()=>D({kind:'player',existing:p})}>Editar</button>}</div>)}</div></>}
{tab==='Avisos'&&<><h1>Avisos</h1>{notes.map(n=><div className="card" key={n.id} style={{marginBottom:8}}>{n.texto}<div className="lbl">{new Date(n.created_at).toLocaleString('es-CO')}</div></div>)}{!notes.length&&<div className="empty">Sin notificaciones.</div>}</>}
{modal&&<Modal data={modal} close={()=>D(null)} session={session} refresh={refresh} toast={toast} notify={createNotification}/>}</main>{msg&&<div id="toast" className="show">{msg}</div>}</>}
function Auth({toast,onAuth}){const [email,E]=useState(''),[password,W]=useState(''),[busy,B]=useState(false);const submit=async mode=>{if(busy)return;if(!email.trim()||!password){toast('Escribe tu correo y contraseña');return}B(true);try{if(mode==='login'){const {data,error}=await window.supabaseClient.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;if(data.session)onAuth(data.session);toast('Sesión iniciada');}else{const {data,error}=await window.supabaseClient.auth.signUp({email:email.trim(),password});if(error)throw error;if(data.session){onAuth(data.session);toast('Cuenta creada');}else toast('Cuenta creada. Revisa tu correo para confirmar la cuenta.');}}catch(e){toast(e.message||'No se pudo completar la operación')}finally{B(false)}};return <main><section><h1>Bienvenido a MATCHDAY</h1><p className="sub">Crea tu cuenta para organizar partidos y jugar con otras personas.</p><form className="card" style={{maxWidth:520}} onSubmit={e=>{e.preventDefault();submit('login')}}><label>Correo electrónico</label><input type="email" value={email} onChange={e=>E(e.target.value)} autoComplete="email" required/><label>Contraseña</label><input type="password" value={password} onChange={e=>W(e.target.value)} autoComplete="current-password" required minLength="6"/><div className="row" style={{marginTop:14}}><button type="submit" className="btn" disabled={busy}>{busy?'Iniciando...':'Iniciar sesión'}</button><button type="button" className="btn g" disabled={busy} onClick={()=>submit('signup')}>Crear cuenta</button></div></form></section></main>}
function MatchCard({m,session,me,reqs,edit,join,remove}){const own=m.owner_id===session.user.id,requested=reqs.some(r=>r.match_id===m.id&&r.player_id===session.user.id&&r.estado==='pendiente');return <div className="card"><span className="badge">{m.modo}</span><span className="badge">{m.nivel}</span><h3>{m.nombre}</h3><div className="lbl">{m.fecha} · {String(m.hora).slice(0,5)} · {m.cancha}</div><p>{m.conf}/{m.max_players} jugadores · $ {Number(m.precio||0).toLocaleString('es-CO')}</p><div className="bar"><i style={{width:Math.min(100,(m.conf||0)/(m.max_players||1)*100)+'%'}}/></div><div className="row">{own?<><button className="btn s g" onClick={edit}>Editar</button><button className="btn s g" onClick={remove}>Eliminar</button></>:<button className="btn s" disabled={!me||requested||m.conf>=m.max_players} onClick={join}>{requested?'Solicitud enviada':!me?'Crea tu perfil':'Quiero jugar'}</button>}</div></div>}
function Modal({data,close,session,refresh,toast,notify}){const [pos,SP]=useState(data.existing?.pos||'Delantero');if(data.kind==='view')return <div className="overlay"><div className="modalbox"><h2>{data.player.nombre}</h2><p>{data.player.pos} · {data.player.equipo}</p>{Object.entries(data.player.stats||{}).map(([k,v])=><div className="lbl" key={k}>{k.replaceAll('_',' ')}: {v}</div>)}<button className="btn g" onClick={close}>Cerrar</button></div></div>;
const submitPlayer=async e=>{e.preventDefault();const f=new FormData(e.target),stats={};[...new Set([...GEN,...POS[pos]])].forEach(k=>stats[k]=Number(f.get('s_'+k)||0));const p={nombre:f.get('nombre'),apodo:f.get('apodo'),num:Number(f.get('num')),pos,equipo:f.get('equipo'),pie:f.get('pie'),nivel:f.get('nivel'),stats};try{if(data.existing){if(data.existing.id!==session.user.id)throw Error('Solo puedes editar tu propio perfil');await MatchdayAPI.updatePlayer(session.user.id,p)}else await MatchdayAPI.createPlayer({id:session.user.id,...p});toast('Perfil guardado');await refresh()}catch(x){toast(x.message)}};
const submitMatch=async e=>{e.preventDefault();const f=new FormData(e.target),m={nombre:f.get('nombre'),modo:f.get('modo'),fecha:f.get('fecha'),hora:f.get('hora'),cancha:f.get('cancha'),max_players:+f.get('max'),precio:+f.get('precio'),nivel:f.get('nivel'),publico:f.get('publico')==='1',faltan:f.getAll('faltan')};try{if(data.existing){if(data.existing.owner_id!==session.user.id)throw Error('Solo el creador puede editar este partido');await MatchdayAPI.updateMatch(data.existing.id,m)}else await MatchdayAPI.createMatch({owner_id:session.user.id,conf:1,descripcion:'',...m});toast('Partido guardado');await notify('Se guardó un partido: '+m.nombre);await refresh()}catch(x){toast(x.message)}};
const submitJoin=async e=>{e.preventDefault();const f=new FormData(e.target);try{await MatchdayAPI.createRequest({match_id:data.match.id,player_id:session.user.id,pos:f.get('pos'),comentario:f.get('comentario'),estado:'pendiente'});toast('Solicitud enviada');await refresh()}catch(x){toast(x.message)}};
return <div className="overlay"><div className="modalbox"><button className="btn s g" style={{float:'right'}} onClick={close}>Cerrar</button>{(data.kind==='player')&&<><h2>{data.existing?'Editar mi perfil':'Crear mi perfil'}</h2><form onSubmit={submitPlayer}><label>Nombre</label><input name="nombre" defaultValue={data.existing?.nombre} required/><label>Apodo</label><input name="apodo" defaultValue={data.existing?.apodo}/><div className="f2"><div><label>Número</label><input name="num" type="number" min="1" max="99" defaultValue={data.existing?.num||1}/></div><div><label>Equipo</label><input name="equipo" defaultValue={data.existing?.equipo}/></div><div><label>Posición</label><select name="pos" value={pos} onChange={e=>SP(e.target.value)}>{Object.keys(POS).map(x=><option key={x}>{x}</option>)}</select></div><div><label>Pie</label><select name="pie" defaultValue={data.existing?.pie||'Derecho'}><option>Derecho</option><option>Izquierdo</option><option>Ambos</option></select></div></div><label>Nivel</label><select name="nivel" defaultValue={data.existing?.nivel||'Intermedio'}><option>Casual</option><option>Intermedio</option><option>Avanzado</option></select><h2>Estadísticas por posición</h2><div className="f2">{[...new Set([...GEN,...POS[pos]])].map(k=><div key={k}><label>{k.replaceAll('_',' ')}</label><input type="number" min="0" name={'s_'+k} defaultValue={data.existing?.stats?.[k]||0}/></div>)}</div><button className="btn" style={{marginTop:14}}>Guardar perfil</button></form></>}
{data.kind==='match'&&<><h2>{data.existing?'Editar partido':'Crear partido'}</h2><form onSubmit={submitMatch}><label>Nombre</label><input name="nombre" defaultValue={data.existing?.nombre} required/><div className="f2"><div><label>Modalidad</label><select name="modo" defaultValue={data.existing?.modo||'Fútbol 7'}>{['Fútbol 5','Fútbol 7','Fútbol 8','Fútbol 11','Personalizado'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Nivel</label><select name="nivel" defaultValue={data.existing?.nivel||'Casual'}><option>Casual</option><option>Intermedio</option><option>Avanzado</option></select></div><div><label>Fecha</label><input type="date" name="fecha" defaultValue={data.existing?.fecha} required/></div><div><label>Hora</label><input type="time" name="hora" defaultValue={data.existing?.hora?.slice(0,5)} required/></div><div><label>Cancha</label><input name="cancha" defaultValue={data.existing?.cancha} required/></div><div><label>Máximo jugadores</label><input name="max" type="number" min="2" defaultValue={data.existing?.max_players||10}/></div><div><label>Precio</label><input name="precio" type="number" min="0" defaultValue={data.existing?.precio||0}/></div><div><label>Visibilidad</label><select name="publico" defaultValue={data.existing?.publico===false?'':'1'}><option value="1">Público</option><option value="">Privado</option></select></div></div><label>Posiciones faltantes</label><select name="faltan" multiple size="4" defaultValue={data.existing?.faltan||[]}>{['Portero','Defensa','Lateral','Mediocampista','Extremo','Delantero','Libre'].map(x=><option key={x}>{x}</option>)}</select><button className="btn" style={{marginTop:14}}>Guardar partido</button></form></>}
{data.kind==='join'&&<><h2>Solicitar unirse a {data.match.nombre}</h2><form onSubmit={submitJoin}><label>Posición</label><select name="pos">{Object.keys(POS).map(x=><option key={x}>{x}</option>)}</select><label>Comentario</label><textarea name="comentario"/><button className="btn" style={{marginTop:14}}>Enviar solicitud</button></form></>}</div></div>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);